#!/bin/sh
basedir=`dirname "$0"`

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/IBMnode/bin/node" ]; then
  "$basedir/IBMnode/bin/node"  "$basedir/mobilefirst-cli/bin/mobilefirst-cli.js" "$@"
  ret=$?
else
  "node"  "$basedir/bin/mobilefirst-cli.js" "$@"
  ret=$?
fi
exit $ret
